name: object_tree
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.3


    ## Widgets
  # List drag and drop
  dad_list:
    path: ./packages/dad_list

  # Open browser
  url_launcher: ^6.3.1

  # Navigation
  go_router: ^14.2.1

  # For keyboard
  flutter_keyboard_visibility: ^6.0.0

    ## Work with files
  # With MD
  flutter_markdown: 
    path: ./packages/flutter_markdown-0.7.6+2
    
  # With DB
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.5

  # With Files
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  file_picker: ^8.1.7
  path: ^1.9.0
  # For permissions
  permission_handler: ^11.3.1

  # State Managment 
  flutter_bloc: ^8.1.6
  # Service locator
  get_it: ^7.6.9

  # Logging
  talker_flutter: ^4.6.0
  talker_bloc_logger: ^4.6.0

  # Localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  slang: ^3.31.2
  slang_flutter: ^3.31.0

  # Equals
  equatable: ^2.0.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/svg/node.svg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
